name: phicare-backend
channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.11.11
  - pip
  - pip:
    - langchain 
    - langchain_core 
    - langchain_huggingface
    - qdrant_client 
    - sentence_transformers 
    - fastembed 
    - python-dotenv 
    - websockets