name: phistem-backend
channels:
  - anaconda
  - conda-forge
dependencies:
  - python==3.11.11
  - langchain 
  - langchain-core 
  - websockets
  - datasets
  - pandas
  - pip
  - pip:
    - langchain_huggingface
    - qdrant_client 
    - fastembed
    - sentence-transformers >= 3.4.1
    - transformers >= 4.48